config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout' }
  resources :users
  resources :products do
    resources :comments
  end
  get 'static_pages/about'

  get '/about' =>'static_pages#about'

  get 'static_pages/contact'

  get '/contact' =>'static_pages#contact'

  get 'static_pages/landing_page' =>'static_pages#landing_page'
  
  get '/landing_page' =>'static_pages#landing_page'
  
  get 'static_pages/index'

  post 'static_pages/thank_you'

  post 'payments/create'

  post 'orders/create'

  get 'static_pages/thank_you' => redirect('/contact')

	root 'static_pages#index'

  mount ActionCable.server => '/cable'

	resources :orders, only: [:index, :show, :create, :destroy]
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :product
  
  validates :body, presence: true
  validates :user, presence: true
  validates :product, presence: true
  validates :rating, numericality: { only_integer: true }
  after_create_commit { CommentUpdateJob.perform_later(self, @user) }
  scope :rating_desc, -> { order(rating: :desc) }

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_user, only: [:destroy]
  before_action :authenticate_user!
  load_and_authorize_resource

	def create
    @product = Product.find(params[:product_id])
    @comment = @product.comments.new(comment_params)
    @comment.user = current_user
    @user = current_user
    respond_to do |format|
      if @comment.save
        #ActionCable.server.broadcast 'product_channel', comment: @comment, average_rating: @comment.product.average_rating
        
        format.html { redirect_to @product, notice: 'Review was created successfully.' }
        format.json { render :show, status: :created, location: @product }
        format.js
      else
        format.html { redirect_to @product, alert: 'Review was not saved successfully.' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    product = @comment.product
    @comment.destroy
    redirect_to product
  end

  private
    def comment_params
      params.require(:comment).permit(:user_id, :body, :rating)
    end

      # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = current_user
    end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
        <div class="row">
            <hr>
            <p><%= comment.user.first_name %> <small><em><%= "#{time_ago_in_words(comment.created_at)} ago" %></em></small>   
            <% if current_user && current_user.admin? %>
            <%= link_to ('<span class="glyphicon glyphicon-remove"></span>').html_safe, product_comment_path(comment.product, comment), method: :delete, data: { confirm: 'Are you sure?' } %>
            <% end %>
            </p>
            <p><%= "Rating: #{comment.rating}/5" %></p>
            <div class="rated" data-score="<%= comment.rating %>"></div>
            <p><%= comment.body %></p>
        </div>

app/views/comments/create.js.erb
$("#new_comment").html("<br><strong>Thank you for your review!</strong>");
$("#average-rating").attr('data-score', "<%= @product.average_rating %>");
refreshRating();