config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout' }
  resources :users
  resources :products do
    resources :comments
  end
  get 'static_pages/about'

  get '/about' =>'static_pages#about'

  get 'static_pages/contact'

  get '/contact' =>'static_pages#contact'

  get 'static_pages/landing_page' =>'static_pages#landing_page'
  
  get '/landing_page' =>'static_pages#landing_page'
  
  get 'static_pages/index'

  post 'static_pages/thank_you'

  post 'payments/create'

  post 'orders/create'

  get 'static_pages/thank_you' => redirect('/contact')

	root 'static_pages#index'

  mount ActionCable.server => '/cable'

	resources :orders, only: [:index, :show, :create, :destroy]
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
	has_many :orders
	has_many :comments
	validates :name, presence: true
	validates :price, numericality: true
	
	def self.search(search_term)
		Product.where("name LIKE ?", "%#{search_term}%")
	end

	def highest_rating_comment
		comments.rating_desc.first
	end
	
	def average_rating
		comments.average(:rating).to_f
	end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :set_user, only: [:create,  :new, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:create, :new, :edit, :update, :destroy]
  load_and_authorize_resource

  # GET /products
  # GET /products.json
  def index

    if params[:q]
      search_term = params[:q]
      @products = Product.search(search_term)
    else
      @products = Product.all
    end

  end

  # GET /products/1
  # GET /products/1.json
  def show
  @comments = @product.comments.order("created_at DESC").paginate(:page => params[:page], :per_page => 5)
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :image_url, :color, :price)
    end
          # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = current_user
    end
end

app/helpers/products_helper.rb
module ProductsHelper
	def cache_key_for_products
    count          = Product.count
    max_updated_at = Product.maximum(:updated_at).try(:utc).try(:to_s, :number)
    "products/all-#{count}-#{max_updated_at}"
  end
end

app/views/products/_comments.html.erb
<h2>Reviews:</h2>
<div class="product-reviews">
    <% @comments.each do |comment| %>
        <%= render comment %>
    <% end %>
    <%= will_paginate @comments %>
</div>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>
      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="container">
  <div class="col-sm-6">
    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name, id: :product_name, class:'form-control' %>
    </div>
      <div class="field">
        <%= form.label :description %>
        <%= form.text_area :description, id: :product_description,class:'form-control' %>
      </div>
      <div class="field">
        <%= form.label :image_url %>
        <%= form.text_field :image_url, id: :product_image_url, class:'form-control'  %>
      </div>
      <div class="field">
      <%= form.label :color %><br>
      <%= form.text_field :color, class:'form-control' %>
      </div>
      <div class="field">
      <%= form.label :price %><br>
      <%= form.text_field :price, class:'form-control' %>
      </div>
      <div class="actions">
        <%= form.submit class:'btn btn-default'%>
      </div>
      <div class="col-sm-6">
      </div>
    </div>
  </div>
<% end %>

app/views/products/_new_comment.html.erb
<% if signed_in? %>
  <%= form_for([@product, @product.comments.build], remote: true) do |f| %>
    <h4>Add a review:</h4>
    <p>
      <%= f.label :body, "Comments" %><br>
      <%= f.text_area :body %>
    </p>
    <p>
    <div class="rating"></div>
    </p>  
    <p>
      <%= f.submit "Submit" %>
    </p>
  <% end %>
<% end %>

app/views/products/_product.html.erb
<% cache product do %>
	<div class="col-sm-2 col-md-4">
	      <% if product.image_url != nil %>
	        <%= image_tag(product.image_url, class: "img-responsive product", height: '250', width: '320') %>
	        <% end %>
	        <h1><%= link_to(product.name,product_path(product)) %></h1>
	        <p><%= product.description %></p>
	        <p><div class="rated" data-score="<%= product.average_rating %>"><strong>Rating: </strong></div></p>
	        <p><strong>Color: </strong><%= product.color %>
	        <p><strong>Price: </strong>$<%= product.price %></p>
	        <%= link_to ('<u>More Details</u>').html_safe, product_path(product) %>
	</div><!-- /col -->
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>


<div class="container-fluid">
  <div class="row">
    <% if @products.count > 0 %>
		<% cache(cache_key_for_products) do %>
    		<%  @products.each do |product| %>
	       		<%= render product %>
	       	<% end %>
    	<% end %>
    <% else %>
    	<br><b> No Products Found</b> <br>
    <% end %>
  </div>
</div>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product Form</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<div class="container">
  <div class="row" data-product-id="<%= @product.id %>">
    <div class="col-xs-12 col-sm-9">
    <% cache @product do %>
      <h1><%= @product.name %></h1>
      <p>
        <%= 
        if (@product.image_url != nil)
         image_tag(@product.image_url, class: "img-responsive product img-zoom", height: '350', width: '350', data_zoom_images:"/assets/"+@product.image_url) 
      	end
         %>
      </p>
      <p>Average Rating: <div class="rated" id="average-rating" data-score="<%= @product.average_rating %>"></div> </p>
      <p><strong>Description:</strong>
      <%= @product.description %></p>
      <p><strong>Color:</strong>
        <%= @product.color %></p>
      <p><strong>Price:</strong>
        <%= @product.price %></p>
      <% end %>
      <%= form_with(url: '/payments/create') do |form| %>
      <%= hidden_field_tag(:product_id, @product.id) %>
      <% if signed_in? %>
        <%= hidden_field_tag(:user_id, current_user.id) %>
        <%= hidden_field_tag(:user_email, current_user.email) %>
      <% end %>
      <%= render partial: "shared/stripe_checkout_button" %>
      <% end %>
      <% if signed_in? && current_user.admin? %>
       <%= link_to 'Edit', edit_product_path(@product) %> |
      <% end %>
      <%= link_to 'Back', products_path %>

    </div>
    <div class="col-sm-3">
    </div>
  </div>
  <div class="row" id="comments-section">
    <div class="col-xs-12 col-sm-9">
      <%= render 'new_comment' %>
      <div class="alert alert-info" style="display:none" role="alert">A new comment has been posted!</div>
      <%= render 'comments' %>
    </div>
    <div class="col-sm-3">
    </div>
  </div>
</div>